language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0
  - jruby-19mode
before_install:
  - gem update --system
install: "bundle install"
script: "bundle exec rake spec"
gemfile:
  - gemfiles/rails3.gemfile
  - gemfiles/rails4_0.gemfile
  - gemfiles/rails4_1.gemfile
  - gemfiles/rails4_2.gemfile
branches:
  only:
    - master